language: php

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache/files

jobs:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4

services:
  - mysql

before_install:
  - mysql -u root --password="" -e 'CREATE DATABASE jmsjobqueue_test;'

before_script:
  - composer self-update
  - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install: composer install 

script: phpunit --coverage-clover clover

